http:
  listener:
    host: "localhost"
    port: "8083"
  requester:
    host: "localhost"
    port: "8081"
    routepath: "/travelOnTripCall/getRoutes"
    schedulepath: "/travelOnTripCall/getSchedules"