#%RAML 1.0 Library
usage:
traits:
  transactionId: !include common/traits/headertransactionIdtrait.raml
  departureLocation: !include common/traits/queryParamdeparturelocationtrait.raml
  destinationLocation: !include common/traits/queryParamdestinationtrait.raml
  

  